export const STATIC_PRODUCTS = [
    {
        id: 1,
        name: 'Kyoto Tea Set',
        price: 185,
        series: 'Kyoto Series',
        image_url: 'assets/images/collections/kyoto/kyoto_tea_set_1773658150672.png',
        tags: 'tea,set,stoneware,kyoto',
        description: 'A ceremonial Kyoto-inspired tea service with a quiet stoneware finish and balanced everyday proportions.',
        contents: 'Includes one hand-thrown teapot, two tasting cups, one serving tray, and a care card.\nPacked in a reusable Miyaki storage box.',
        size: 'Teapot: 18 cm W x 12 cm H; Cups: 7 cm W x 6 cm H',
    },
    {
        id: 2,
        name: 'Kyoto Matcha Bowl',
        price: 65,
        series: 'Kyoto Series',
        image_url: 'assets/images/collections/kyoto/kyoto_matcha_bowl_1773658166896.png',
        tags: 'matcha,bowl,kyoto',
        description: 'A hand-shaped matcha bowl made for whisking, serving, and display, with a soft studio-glazed interior.',
        contents: 'Includes one matcha bowl and one studio care card.\nRecommended pairing: bamboo whisk from the Kyoto Series.',
        size: 'Approx. 12 cm W x 7 cm H',
    },
    {
        id: 3,
        name: 'Kyoto Bamboo Whisk',
        price: 35,
        series: 'Kyoto Series',
        image_url: 'assets/images/collections/kyoto/kyoto_bamboo_whisk_1773658183135.png',
        tags: 'matcha,whisk,bamboo,kyoto',
        description: 'A traditional bamboo whisk selected for smooth matcha preparation and compact counter storage.',
        contents: 'Includes one bamboo whisk, one ceramic whisk stand, and one care card.\nDesigned for daily matcha preparation.',
        size: 'Approx. 11 cm L x 5 cm W',
    },
    {
        id: 4,
        name: 'Obsidian Vase Set',
        price: 145,
        series: 'Obsidian Collection',
        image_url: 'assets/images/collections/obsidian/obsidian_vase_set_1773658203257.png',
        tags: 'vase,obsidian,centerpiece',
        description: 'A sculptural obsidian vessel grouping with dark mineral texture, designed as a dramatic table centerpiece.',
        contents: 'Includes one primary vessel and protective packaging.\nEach piece may vary slightly in glaze, texture, and finish.',
        size: 'Tallest vessel: approx. 24 cm H; set footprint: 32 cm W',
    },
    {
        id: 5,
        name: 'Obsidian Incense Holder',
        price: 45,
        series: 'Obsidian Collection',
        image_url: 'assets/images/collections/obsidian/obsidian_incense_holder_1773658222406.png',
        tags: 'incense,obsidian,ritual',
        description: 'A low-profile incense holder with a dark fired surface and a restrained ritual presence.',
        contents: 'Includes one incense holder and care card.',
        size: 'Approx. 16 cm L x 4 cm W',
    },
    {
        id: 6,
        name: 'Obsidian Textural Plate',
        price: 75,
        series: 'Obsidian Collection',
        image_url: 'assets/images/collections/obsidian/obsidian_plate_1773658242833.png',
        tags: 'plate,obsidian,tableware',
        description: 'A textural black plate with an uneven edge, made for quiet plating and display.',
        contents: 'Includes one plate and studio care card.',
        size: 'Approx. 24 cm diameter',
    },
    {
        id: 7,
        name: 'Obsidian Minimal Stack',
        price: 210,
        series: 'Obsidian Collection',
        image_url: 'assets/images/collections/obsidian/obsidian_stack.png',
        tags: 'stack,obsidian,tableware',
        description: 'A minimal stacked tableware set in deep obsidian tones for layered dining.',
        contents: 'Includes stacked plates and bowls from the Obsidian Collection.',
        size: 'Stack height: approx. 18 cm',
    },
    {
        id: 8,
        name: 'Terracotta Dining Set',
        price: 280,
        series: 'Fire and Mud',
        image_url: 'assets/images/collections/earthenware/terracotta_dining_set_1773657139828.png',
        tags: 'terracotta,dining,set',
        description: 'A warm terracotta dining set shaped for generous everyday meals and long table settings.',
        contents: 'Includes dinner plates, side plates, bowls, and serving pieces.',
        size: 'Service set for four.',
    },
    {
        id: 9,
        name: 'Earthen Plate',
        price: 55,
        series: 'Fire and Mud',
        image_url: 'assets/images/collections/earthenware/earthen_plate_1773657156482.png',
        tags: 'plate,earthenware,terracotta',
        description: 'A single earthen plate with a grounded clay body and soft handmade irregularity.',
        contents: 'Includes one plate and studio care card.',
        size: 'Approx. 23 cm diameter',
    },
    {
        id: 10,
        name: 'Clay Pitcher',
        price: 85,
        series: 'Fire and Mud',
        image_url: 'assets/images/collections/earthenware/clay_pitcher_1773657175884.png',
        tags: 'pitcher,clay,serving',
        description: 'A hand-thrown clay pitcher made for water, tea, or branch arrangements.',
        contents: 'Includes one pitcher.',
        size: 'Approx. 19 cm H',
    },
    {
        id: 11,
        name: 'Mug Duo',
        price: 60,
        series: 'Fire and Mud',
        image_url: 'assets/images/collections/earthenware/mug_duo_1773657192012.png',
        tags: 'mug,duo,earthenware',
        description: 'A paired mug set with warm clay tones and comfortable everyday handles.',
        contents: 'Includes two mugs.',
        size: 'Approx. 300 ml each',
    },
    {
        id: 12,
        name: 'Artisan Hands Decorative',
        price: 0,
        series: 'Kyoto Series',
        image_url: 'assets/images/artisan_hands.png',
        tags: 'studio,decorative,process',
        description: 'A decorative studio image included to show the Miyaki making process.',
        contents: 'Decorative studio asset.',
        size: 'Digital image asset.',
    },
    {
        id: 13,
        name: 'Test Bowl',
        price: 50,
        series: 'Kyoto Series',
        image_url: 'assets/images/vases.png',
        tags: 'test,bowl',
        description: 'A test ceramic bowl entry used for layout and collection checks.',
        contents: 'Includes one test piece.',
        size: 'Studio sample dimensions.',
    },
    {
        id: 15,
        name: 'Test Dropdown Item',
        price: 99,
        series: 'Kyoto Series',
        image_url: 'assets/images/vases.png',
        tags: 'test,dropdown',
        description: 'A test item used to confirm dropdown, product detail, and specification behavior.',
        contents: 'Includes test item contents and specification placeholders.',
        size: 'Test item dimensions.',
    },
];

export const STATIC_SERIES_META = [
    {
        name: 'Kyoto Series',
        description: 'Quiet tea objects and ritual pieces inspired by Kyoto forms, soft glazes, and everyday ceremony.',
    },
    {
        name: 'Obsidian Collection',
        description: 'Dark mineral surfaces, sculptural silhouettes, and table objects with a dramatic studio presence.',
    },
    {
        name: 'Fire and Mud',
        description: 'Warm terracotta clay bodies, generous dining forms, and grounded everyday tableware.',
    },
];

export const STATIC_EVENTS = [];
